### PR TITLE
Use mod.conf for dependencies

### PR DESCRIPTION
**Pull request by Panquesito7**
Deletes deprecated `depends.txt`.

### CODE REVIEW

**Comment by spixi** [comment]
Is that backwards-compatible or will this break older versions of minetest?

**Comment by Panquesito7** [comment]
It'll break older versions of Minetest (0.4.17.1 and below).
This is the new method for dependencies/description, however.

**Comment by spixi** [comment]
Thank you. I first have to test whether this mod still works on 5.0.0 or if there are further changes to be done, before I can merge this PR.

**Comment by Panquesito7** [comment]
It should work properly; I have a mod which uses mod.conf and works.
However, it works only with MT/MTG 5.0.0+.

**Comment by spixi** [comment]
Unfortunately, this mod is not compatible with 5.0.0 at the moment.

1. ~~the new function returned by minetest.get_translator() is unable to work with the return value of string.gsub (needs a single value instead of a pair of values)~~
**Can be fixed with parentheses around the r:gsub call**
2. ~~I have currently found no way to access the textures from the default mod (error message generateImage(): Could not load image "default_desert_stone_block.png" while building texture; Creating a dummy image)~~
**Was my fault, this depends on default and I did not load default**
3. If you use the burin, the nodes break when they are not supposed to.
**Still has to be fixed**
4. Burins break much faster than intended.
**Still has to be fixed**

It is not just changing this. There needs a lot of more changes to be done to make this mod working with 5.0.0

**Comment by spixi** [comment]
I implemented the feature now.

**Comment by sofar** [comment]
>It is not just changing this. There needs a lot of more changes to be
>done to make this mod working with 5.0.0

Old versions will continue to work with 0.4.x.... is there a reason that making this work with 5.x is taking so long?

**Comment by spixi** [comment]
> It is not just changing this. There needs a lot of more changes to be done to make this mod working with 5.0.0
> Old versions will continue to work with 0.4.x.... is there a reason that making this work with 5.x is taking so long?

It should work now with 5.x

**Comment by Panquesito7** [comment]
@spixi, you may want to delete `depends.txt` as it's useless now. 😉

**Comment by spixi** [comment]
@Panquesito7, thank you. I forgot to `git add` the deleted `depends.txt`.

**Pull request merged**
